name: Update Contributors

on:
  push:
    branches:
      - main # Change this to your default branch if it's not main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get contributors
        id: contributors
        run: |
          # Fetch contributors and format them
          contributors=$(git log --format='%aN <%aE>' | sort -u | awk '{printf "- **%s** - [GitHub Profile](https://github.com/%s)\n", $1, $1}')
          echo "::set-output name=contributors::$contributors"

      - name: Update README.md
        run: |
          # Check if Contributors section exists
          if grep -q "## Contributors" README.md; then
            # Append contributors only if not already in the list
            existing_contributors=$(sed -n '/## Contributors/,/##/p' README.md | sed '1d;$d')
            for contributor in ${{ steps.contributors.outputs.contributors }}; do
              if ! echo "$existing_contributors" | grep -q "$contributor"; then
                echo "$contributor" >> README.md
              fi
            done
          else
            echo "## Contributors" >> README.md
            echo "${{ steps.contributors.outputs.contributors }}" >> README.md
          fi

      - name: Commit changes
        run: |
          git config --local user.email "you@example.com" # replace with your email
          git config --local user.name "GitHub Action" # replace with a name you want to use
          git add README.md
          git commit -m "Update contributors list"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
